export const translations = {
  fr: {
    title: "AgroScan IA",
    subtitle: "L'IA au service de l'agronomie moderne",
    connect: "Se connecter avec Google",
    scan: "Scanner",
    map: "Carte",
    catalog: "Répertoire",
    region: "Région",
    family: "Famille",
    domain: "Domaine/Site",
    search: "Rechercher une variété...",
    filters: "Filtres",
    reset: "Réinitialiser",
    export: "Exporter CSV",
    weather: "Météo Locale",
    manualLocation: "Localisation manuelle",
    save: "Enregistrer",
    delete: "Supprimer",
    retry: "Réessayer l'analyse",
    week: "Cette semaine",
    month: "Ce mois",
    quarter: "Ce trimestre",
    custom: "Intervalle personnalisé",
    allUsersReset: "Réinitialiser pour tous",
    accessPending: "Demande d'accès en attente",
    accessPendingDesc: "Votre demande d'accès est en cours de validation par un administrateur. Vous recevrez une notification une fois approuvée.",
    accessRejected: "Accès refusé",
    accessRejectedDesc: "Désolé, votre demande d'accès a été refusée. Veuillez contacter le support pour plus d'informations.",
    requestAccess: "Demander l'accès",
    logout: "Se déconnecter",
    temp: "Température",
    humidity: "Humidité",
    wind: "Vent",
    precip: "Précipitations",
    forecast: "Prévisions 3 jours",
    satellite: "Satellite",
    standard: "Standard",
    noResults: "Aucun résultat ne correspond à vos critères.",
    loading: "Chargement...",
    offline: "HORS LIGNE",
    notes: "Notes de l'agronome",
    analysis: "Analyse IA",
    recent: "Analyses Récentes",
    pending: "En attente...",
    error: "Échec de l'analyse",
    success: "Analyse réussie",
    admin: "Administration",
    users: "Utilisateurs",
    approve: "Approuver",
    reject: "Refuser",
    status: "Statut",
    role: "Rôle",
    pendingUsers: "Demandes en attente",
    allUsers: "Tous les utilisateurs",
    accessApproved: "Accès approuvé",
    login: "Connexion",
    signup: "S'inscrire",
    email: "Email",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    resetPassword: "Réinitialiser le mot de passe",
    sendResetEmail: "Envoyer l'email de réinitialisation",
    verifyEmail: "Veuillez vérifier votre email",
    verifyEmailDesc: "Un email de vérification a été envoyé. Veuillez cliquer sur le lien pour activer votre compte.",
    invalidCredentials: "Identifiants invalides",
    accountLocked: "Compte verrouillé. Trop de tentatives.",
    networkIssue: "Problème de réseau. Veuillez vérifier votre connexion.",
    authError: "Erreur d'authentification",
    observationDetails: "Détails de l'observation",
    userCatalog: "Répertoires par utilisateur",
    viewCatalog: "Voir le répertoire",
    back: "Retour",
    quotaExceeded: "Quota Firestore dépassé. Veuillez réessayer demain.",
    select: "Sélect.",
    cancel: "Annuler",
    tempMax: "Temp Max",
    tempMin: "Temp Min",
    tempAvg: "Temp Moyenne",
    humidityRel: "Humidité Relative",
    et0: "ET0 FAO",
    dpv: "DPV (VPD)",
    par: "Rayonnement (PAR)",
    precipQty: "Quantité Précip.",
    precipProb: "Probabilité Précip.",
    windSpeed: "Vitesse Vent",
    airQuality: "Qualité Air (Poussière)",
    searchLocation: "Rechercher un site ou une ville",
    nearestSite: "Site le plus proche",
  },
  en: {
    title: "AgroScan AI",
    subtitle: "AI at the service of modern agronomy",
    connect: "Sign in with Google",
    scan: "Scan",
    map: "Map",
    catalog: "Catalog",
    region: "Region",
    family: "Family",
    domain: "Domain/Site",
    search: "Search for a variety...",
    filters: "Filters",
    reset: "Reset",
    export: "Export CSV",
    weather: "Local Weather",
    manualLocation: "Manual Location",
    save: "Save",
    delete: "Delete",
    retry: "Retry Analysis",
    week: "This week",
    month: "This month",
    quarter: "This quarter",
    custom: "Custom interval",
    allUsersReset: "Reset for all",
    accessPending: "Access Request Pending",
    accessPendingDesc: "Your access request is being validated by an administrator. You will be notified once approved.",
    accessRejected: "Access Denied",
    accessRejectedDesc: "Sorry, your access request has been denied. Please contact support for more information.",
    requestAccess: "Request Access",
    logout: "Logout",
    temp: "Temperature",
    humidity: "Humidity",
    wind: "Wind",
    precip: "Precipitation",
    forecast: "3-Day Forecast",
    satellite: "Satellite",
    standard: "Standard",
    noResults: "No results match your criteria.",
    loading: "Loading...",
    offline: "OFFLINE",
    notes: "Agronomist Notes",
    analysis: "AI Analysis",
    recent: "Recent Analyses",
    pending: "Pending...",
    error: "Analysis failed",
    success: "Analysis successful",
    admin: "Administration",
    users: "Users",
    approve: "Approve",
    reject: "Reject",
    status: "Status",
    role: "Role",
    pendingUsers: "Pending Requests",
    allUsers: "All Users",
    accessApproved: "Access Approved",
    login: "Login",
    signup: "Sign Up",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    sendResetEmail: "Send Reset Email",
    verifyEmail: "Please verify your email",
    verifyEmailDesc: "A verification email has been sent. Please click the link to activate your account.",
    invalidCredentials: "Invalid credentials",
    accountLocked: "Account locked. Too many attempts.",
    networkIssue: "Network issue. Please check your connection.",
    authError: "Authentication error",
    observationDetails: "Observation Details",
    userCatalog: "Catalogs by user",
    viewCatalog: "View catalog",
    back: "Back",
    quotaExceeded: "Firestore quota exceeded. Please try again tomorrow.",
    select: "Select",
    cancel: "Cancel",
    tempMax: "Max Temp",
    tempMin: "Min Temp",
    tempAvg: "Avg Temp",
    humidityRel: "Relative Humidity",
    et0: "ET0 FAO",
    dpv: "VPD",
    par: "Radiation (PAR)",
    precipQty: "Precip. Qty",
    precipProb: "Precip. Prob.",
    windSpeed: "Wind Speed",
    airQuality: "Air Quality (Dust)",
    searchLocation: "Search for a site or city",
    nearestSite: "Nearest site",
  },
  ar: {
    title: "أجرو سكان ذكاء اصطناعي",
    subtitle: "الذكاء الاصطناعي في خدمة الزراعة الحديثة",
    connect: "تسجيل الدخول باستخدام جوجل",
    scan: "مسح",
    map: "خريطة",
    catalog: "الفهرس",
    region: "الجهة",
    family: "الفصيلة",
    domain: "المجال/الموقع",
    search: "البحث عن صنف...",
    filters: "الفلاتر",
    reset: "إعادة تعيين",
    export: "تصدير CSV",
    weather: "الطقس المحلي",
    manualLocation: "الموقع اليدوي",
    save: "حفظ",
    delete: "حذف",
    retry: "إعادة محاولة التحليل",
    week: "هذا الأسبوع",
    month: "هذا الشهر",
    quarter: "هذا الفصل",
    custom: "فترة مخصصة",
    allUsersReset: "إعادة تعيين للجميع",
    accessPending: "طلب الوصول قيد الانتظار",
    accessPendingDesc: "يتم التحقق من طلب الوصول الخاص بك من قبل المسؤول. سيتم إخطارك بمجرد الموافقة.",
    accessRejected: "تم رفض الوصول",
    accessRejectedDesc: "عذرًا، تم رفض طلب الوصول الخاص بك. يرجى الاتصال بالدعم لمزيد من المعلومات.",
    requestAccess: "طلب الوصول",
    logout: "تسجيل الخروج",
    temp: "درجة الحرارة",
    humidity: "الرطوبة",
    wind: "الرياح",
    precip: "هطول الأمطار",
    forecast: "توقعات 3 أيام",
    satellite: "قمر صناعي",
    standard: "قياسي",
    noResults: "لا توجد نتائج تطابق معاييرك.",
    loading: "جاري التحميل...",
    offline: "غير متصل",
    notes: "ملاحظات المهندس الزراعي",
    analysis: "تحليل الذكاء الاصطناعي",
    recent: "التحليلات الأخيرة",
    pending: "قيد الانتظار...",
    error: "فشل التحليل",
    success: "نجاح التحليل",
    admin: "الإدارة",
    users: "المستخدمين",
    approve: "موافقة",
    reject: "رفض",
    status: "الحالة",
    role: "الدور",
    pendingUsers: "الطلبات المعلقة",
    allUsers: "كل المستخدمين",
    accessApproved: "تمت الموافقة",
    login: "تسجيل الدخول",
    signup: "تسجيل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    resetPassword: "إعادة تعيين كلمة المرور",
    sendResetEmail: "إرسال بريد إعادة التعيين",
    verifyEmail: "يرجى التحقق من بريدك الإلكتروني",
    verifyEmailDesc: "تم إرسال بريد تحقق. يرجى النقر على الرابط لتفعيل حسابك.",
    invalidCredentials: "بيانات الاعتماد غير صالحة",
    accountLocked: "تم قفل الحساب. محاولات كثيرة جدًا.",
    networkIssue: "مشكلة في الشبكة. يرجى التحقق من اتصالك.",
    authError: "خطأ في المصادقة",
    observationDetails: "تفاصيل الملاحظة",
    userCatalog: "الفهارس حسب المستخدم",
    viewCatalog: "عرض الفهرس",
    back: "عودة",
    quotaExceeded: "تم تجاوز حصة Firestore. يرجى المحاولة غدًا.",
    select: "اختر",
    cancel: "إلغاء",
    tempMax: "أقصى حرارة",
    tempMin: "أدنى حرارة",
    tempAvg: "متوسط الحرارة",
    humidityRel: "الرطوبة النسبية",
    et0: "التبخر النتحي",
    dpv: "عجز ضغط البخار",
    par: "الإشعاع النشط ضوئياً",
    precipQty: "كمية الأمطار",
    precipProb: "احتمال الأمطار",
    windSpeed: "سرعة الرياح",
    airQuality: "جودة الهواء (الغبار)",
    searchLocation: "البحث عن موقع أو مدينة",
    nearestSite: "أقرب موقع",
  }
};

export const AGRO_DOMAINS = [
  "Site Nord", "Site Sud", "Verger A", "Verger B", "Parcelle 101", "Serre Expérimentale"
];

export const CULTURES = [
  "Pomme", "Poire", "Pêche", "Abricot", "Cerise", "Prune", "Raisin", "Agrumes", "Autre"
];

export const MOROCCAN_REGIONS = [
  "Tanger-Tétouan-Al Hoceïma",
  "L'Oriental",
  "Fès-Meknès",
  "Rabat-Salé-Kénitra",
  "Béni Mellal-Khénifra",
  "Casablanca-Settat",
  "Marrakech-Safi",
  "Drâa-Tafilalet",
  "Souss-Massa",
  "Guelmim-Oued Noun",
  "Laâyoune-Sakia El Hamra",
  "Dakhla-Oued Ed-Dahab"
];
